import React from 'react';
import InzGlobalStyles from '../components/InzGlobalStyles';
import InzHero from '../components/InzHero';
import InzTextSection from '../components/InzTextSection';

export default function DigestPage() {
  return (
    <>
      <InzGlobalStyles />
      <InzHero
        headline="Trade Intelligence Digest"
        sub="Weekly, LLM-summarised, human-reviewed intelligence on India–NZ trade news — with source citations."
        primaryCta="Subscribe"
        primaryHref="#"
      />
      <InzTextSection title="Latest issue">
        <p>[[Latest published digest summary cards with source citations. Pull from the digest pipeline CMS.]]</p>
      </InzTextSection>
      <InzTextSection title="Archive" bg="light">
        <p>[[Filter by date/topic. Only render items with CMS status = published.]]</p>
        <div style={{ background: '#f6f5f8', padding: '1.5rem', borderRadius: '10px', marginTop: '2rem' }}>
          <p style={{ margin: 0, fontSize: '0.875rem', color: '#61145f' }}>
            <strong>How it's produced:</strong> The Digest is generated by an LLM pipeline and reviewed by a named human reviewer before publication. [[Reviewer name — OI-5.]]
          </p>
        </div>
      </InzTextSection>
    </>
  );
}
